### ISSUE TITLE
Manually continue pcr method

### ISSUE THREAD

**Issue by ngamarra** [BjornFJohansson/pydna#117]
Hello!

I am having a minor issue when attempting pcr. When I attempt to run in python 3.7 in a jupyter notebook it raises pdb at the following lines.

```
> /Users/ngamarra/Library/Python/3.7/lib/python/site-packages/pydna/amplify.py(528)pcr()
-> if hasattr(s, "watson"):
(Pdb) c
> /Users/ngamarra/Library/Python/3.7/lib/python/site-packages/pydna/amplify.py(527)pcr()
-> breakpoint()
(Pdb) c
> /Users/ngamarra/Library/Python/3.7/lib/python/site-packages/pydna/amplify.py(528)pcr()
-> if hasattr(s, "watson"):
(Pdb) c
...
```

This isn't too annoying for one amplicon, but I am trying to amplify several hundred sites in batch and having to manually continue is a bit of pain...

**Comment by BjornFJohansson** [comment]
Hi, can you tell me what version of pydna and biopython you are using? There might have been a version where I left some breakpoints in the code.

**Comment by ngamarra** [comment]
Done! Works great! Thanks!!
