### ISSUE TITLE
Adding the vector to insert duplicated the digestion enzyme

### ISSUE THREAD

**Issue by LuisaFJimenez** [BjornFJohansson/pydna#132]
Dear Bjorn, 
Thanks for the program! It is the perfect solution for my search of establishing my lab under Open Science principles. Yesterday we tried pydna for the first time and we encountered a small issue with the simulation of the cloning. 

- I did a digestion of the vector and the insert using NdeI and XhoI. When using vector + insert, the XhoI site was duplicated (kind of) at the end of my insert site, however when I did insert + vector everything seemed fine: one NdeI site and one XhoI. It seemed to me that the overhang of the XhoI did not assembled correctly and kind of partially duplicated. I cannot rule out 100% we made a mistake looking at the connection, but we were two people revising it.
- The second issue I found was an error when  using the Amplicon object. I added the primers as SeqRecord and when trying to use the function figure() to show the fragment, it tells me "AttributeError: 'SeqRecord' object has no attribute 'footprint'"

 I just wanted to let you know. I love the work you are doing here and if you think we can help you with something, please let me know!

**Comment by BjornFJohansson** [comment]
Hi and thanks for your feedback. Would you be able to share the data and the code you used?
