### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by jefe-jeff** [BjornFJohansson/pydna#133]
Currently, if you run primer_design on a fragment that's too short, it sets off an infinite loop. Perhaps it could throw an error instead? Following example should reproduce the problem. 

`from pydna.design import primer_design`
`from pydna.all import *`
`fragment = Dseqrecord("GCCACCATGG")`
`primer_design(fragment)`

**Comment by BjornFJohansson** [comment]
Thank you for taking the time to report this. Indeed an undesirable behaviour.

**Comment by manulera** [comment]
This does not seem to happen anymore @BjornFJohansson. Should we close?

**Comment by BjornFJohansson** [comment]
yes!
