### ISSUE TITLE
Should molecules with overhangs be allowed to be circular?

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#149]
Hi @BjornFJohansson. I was working on the previous issue when I realise you can create a sequence like this:

```python
from pydna.dseq import Dseq

a = Dseq(watson='AAAA', crick='TTTTG', circular=True)
print(a.__repr__())
print(a.circular)
```

Returns:
```
Dseq(o5)
 AAAA
GTTTT
True
```
Is there a use-case for this type of sequence to be allowed?

**Comment by BjornFJohansson** [comment]
Hi, I used to have lots of sanity checks in the __init__ functions but I removed them to speed things up.
My rationale was that Dseq objects (for my use cases) were almost never made by hand. 
This is open to change though.

**Comment by manulera** [comment]
Yes, that makes sense, there is probably no need to be stringent about it.
