### ISSUE TITLE
Using poetry dependencies in github actions

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#152]
Hi @BjornFJohansson,

I saw that the python dependencies for github actions are taken from yaml files, as far as I understand it, these do not use the poetry file info. Maybe it would be better to install the dependencies using poetry in the actions as well.

The tests at least can be ran like that, with what I mention in the new readme:

```bash
# If you want the virtual environment to be created in this folder
poetry config virtualenvs.in-project true

# Install dependencies (extras are required for tests to pass)
poetry install --all-extras

# Activate virtual environment
poetry shell
```

The action could look like this one:

https://github.com/manulera/ShareYourCloning_backend/blob/67b4ec7731fb42c8187a7fd64491c37afc48a0ed/.github/workflows/ci.yml#L12-L23

**Comment by BjornFJohansson** [comment]
I agree! I used to build conda packages, but stopped since they're no longer absolutely needed. They also take forever to build.

**Comment by BjornFJohansson** [comment]
This is done, but I have problems with Python 3.12

https://github.com/BjornFJohansson/pydna/actions/runs/7140278279/job/19445230849

There is some dependency issue I did not manage to solve

**Comment by manulera** [comment]
I can have a go at this one

**Comment by BjornFJohansson** [comment]
Thanks! Very grateful!  There are problems with 3.8 on some branches, but its just a transfer
of an auxillary function.

**Comment by manulera** [comment]
Hi @BjornFJohansson I think the cause of the problem is numpy 1.24 being incompatible with python 3.12 due to distutils, see https://github.com/numpy/numpy/issues/23808

If the support for 3.8 is dropped in the dependencies, the tests pass:

https://github.com/BjornFJohansson/pydna/actions/runs/7221690221/job/19677189636

Funnily enough, ubuntu-latest with python 3.8 switches to 3.10 and passes the tests https://github.com/BjornFJohansson/pydna/actions/runs/7221690221/job/19677192185#step:8:13:

```
The currently activated Python version 3.8.18 is not supported by the project (>=3.9).
Trying to find and use a compatible version. 
Using python3.10 (3.10.12)
Creating virtualenv pydna-COc8hQSf-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
```
I don't

**Comment by manulera** [comment]
Hi @BjornFJohansson I managed to fix this with https://github.com/BjornFJohansson/pydna/pull/177

This is what changed in pyproject.toml:

```
prettytable = ">=3.5.0"
pyfiglet = "0.8.post1"
pyperclip = { version = ">=1.8.2", optional = true }
scipy = { version = ">=1.9.3", optional = true }
numpy = [
  {version = ">1.26", python = ">=3.9"},
  {version = "<1.24", python = "<3.9"}
]
scipy = [
  {version = ">=1.11.3", python = ">=3.12", optional = true},
  {version = ">=1.9.3", python = "<3.12", optional = true}
]
matplotlib = { version = ">=3.4.3", optional = true }
pillow = { version = ">=8.4.0", optional = true }
pyparsing = { version = ">=2.4.7", optional = true }
```

The dependencies are installed, but the tests do not pass for different reasons, including the Tm thing that you mentioned. Maybe it's easier if you just re-include this changes in the pyproject.toml file of the "right branch" instead of merging, up to you!

To include them on the branch:
* Delete `poetry.lock`
* Remove the virtual environment dir if it's there `rm -rf .venv`
* `poetry install`

That should do the trick

**Comment by BjornFJohansson** [comment]
Found almost the same solution, see dev_bjorn branch. Added benefit is that I know know a bit more of poetry.
I still have to figure out why this didnt happen automatically.

**Comment by manulera** [comment]
Alright! I will close this issue now, you can re-open if you think something is left to be discussed
