### ISSUE TITLE
what is pos in Dseq?

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#153]
Hi @BjornFJohansson,

Sorry for the avalanche of issues! I was looking at the Dseq class and I noticed the argument `pos` in some of the methods. I had a look but I don't understand what this is used for. What is it for? Do I need to worry about it in #147?

**Comment by BjornFJohansson** [comment]
Good question. This might be cruft from something old. let me check.

**Comment by manulera** [comment]
Ok got it!
