### ISSUE TITLE
Separating detection of cutsites from cutting

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#157]
Hi @BjornFJohansson, we discussed this in our call.

The idea would be to separate the `cut` functionality in `Dseqrecord` into two separate functions:

* One that finds the cutting positions, and returns them as sequence features.
* One that executes the cut of the sequence based on that feature.

All this keeping the functionality of `.cut` the same.

**Comment by BjornFJohansson** [comment]
That could be a good idea! I realized today that I would have liked that myself.
