### ISSUE TITLE
python 3?

### ISSUE THREAD

**Issue by hgbrian** [BjornFJohansson/pydna#19]
Hi Bjorn,
first, this is a terrific library and something I've been looking for. I've been enjoying using it (though I just started...)

However, because I have recently been using python3 in general (partially due to snakemake being python3-only), I decided to run 2to3 on pydna to see if it would work. It works, though there were a few things I had to change after 2to3 (and I've only looked at the code when it breaks, so I haven't tested too much). I wasn't really intending to do this, so I didn't even fork it...

Are there plans to make a python3-compatible version?

The changes after 2to3 were the following:

- replacing / with // (integer division) in tools_karkkainen_sanders.py
- replacing python2 bytes with a python3 string in __init__.py (always a python3 bugbear)
- one sort-of bug due to scope changes in python3 that is probably worth changing in python2 too:

`last_pos = [p.pop(0)-max(0,enzyme.ovhg)-1 for (p,e) in
                         sorted([(enzyme.search(Seq(self.seq.dsdata),
                                                linear = self.linear)[::-1],
                                   enzyme) for enzyme in enzymes]) if p]
`
changed to
`last_pos = [p.pop(0)-max(0,e.ovhg)-1 for (p,e) in
                         sorted([(enzyme.search(Seq(self.seq.dsdata),
                                                linear = self.linear)[::-1],
                                   enzyme) for enzyme in enzymes]) if p]
`

Making the library compatible with both python2 and python3 might be a bit more challenging, but I thought I would ask about it anyway. 
Thanks!

**Comment by BjornFJohansson** [comment]
Hi,

I have been thinking of making a python 3 version of the library or allowing both version with the same code. I have an old fork that at least allow import of pydna, but I did not go further with it.

I use the library in my teaching, and python 3 is a bit more pedagogic than 2.7.  

Do you have a fork with the changes you mention? I have no experience with the 2to3 tool, but I understood it is able to make changes automatically? Unfortunately, I have not so much time at the moment, but I would be willing to go ahead with this if you are willing to participate.

Thanks!

**Comment by hgbrian** [comment]
Hi Bjorn,
great! I started using python3 pretty recently, and it seems to be catching on pretty quickly at last... snakemake dropping support for python2 was eye-opening.

You can take a look at https://github.com/hgbrian/pydna
"All" tests pass (see below!)

There were plenty of issues along the way:
- 2to3 had a problem with versioneer.py. I didn't follow it up properly.
- I had to make an odd change to pint to get it to work with doctests https://github.com/hgbrian/pydna/commit/232831b3dc64e55b6e1ff58e90114429fdcacd35
- I had to sometimes choose between bytes and strings. It was difficult to make this consistent. My general rule was to decode anything that came out of a tf.read(). But, when testing if a file is a certain format, I kept it as bytes. I find this part of python3 confusing, even though it's more correct.
- I had to make a \_\_hash\_\_ for Dseqrecord. I don't have great confidence in this code for various reasons. SeqRecord does not have a \_\_hash\_\_ either if I remember correctly?

The weirdest thing is that test_assemble_MX4blaster12.py still fails approximately 50% of the time!
This has been difficult to track down... Perhaps you remember some probabilistic element there?

In this fork, I didn't make any changes that are not strictly python2->python3 (apart from replacing ''' with """ in gel.py since it was inconsistent and messing up my commenting-out). 

Since test coverage is not complete, there are certainly other changes that need to be made (other file formats, for example). This version is certainly good enough for me to use though.

Thanks!

**Comment by BjornFJohansson** [comment]
It seems that the new [IPython 5.0.0](http://blog.jupyter.org/2016/07/08/ipython-5-0-released/) will be the last version to support python 2.x. This finally tipped the scales for me, the next major release will be python 3. 

I have not yet looked into your code, but I will as soon as I have put out the grades of my students.

**Comment by BjornFJohansson** [comment]
The python 3 version in branch py3 works and passes all tests.
