### ISSUE TITLE
Duplicated assembly products if fragments contain overlapping matches

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#200]
A bit of an edge case, but when two overlapping matches exist, we may get duplicated assemblies, or edges that represent the same join. Below a minimal example.

```python
from pydna.common_sub_strings import common_sub_strings

for match in common_sub_strings('AATTAATTAATT', 'AATTAATTAAGG', 8):
    print(match)

# prints
# (0, 0, 10)
# (4, 0, 8)
```

I don't think there is much to do about it, but it's good to keep in mind that this can happen.

**Comment by BjornFJohansson** [comment]
I think these should be returned as two distinctive results. This is typically important in the planning stage and is sometimes due to a planning error or oversight.

```
AATTAATTAATT
0123456789
AATTAATTAAGG


AATTAATTAATT
    01234567
    AATTAATTAAGG
```

**Comment by manulera** [comment]
Hi @BjornFJohansson I am not sure what the point was here. Looking back at it, I don't really understand what I was trying to say.
