### ISSUE TITLE
Merge and new release pydna-6.0.0a29

### ISSUE THREAD

**Issue by BjornFJohansson** [BjornFJohansson/pydna#207]
@manulera, I would like to merge dev_bjorn into main and make a new alpha release (6.0.0a29).
I have updated checksums that depends on a new version of the seguid package throughout.

Anything preventing this?

**Comment by manulera** [comment]
I don't think so! Go ahead and try with the PR. I have not added anything to any branch relying on main in a while.

**Comment by BjornFJohansson** [comment]
OK, done.
