### ISSUE TITLE
Gel exposure / Calculation of ladder quantity

### ISSUE THREAD

**Issue by FinweNoldoran** [BjornFJohansson/pydna#21]
I was attempting to replicate the Jupyter Notebook containing the example of a gel. 

    pydna.Gel([ st,[pcr_prod]] ).run()

When I run this, the ladder is underexposed:

![screen shot 2016-07-15 at 14 03 51](https://cloud.githubusercontent.com/assets/7610184/16888480/0c7c7cec-4a95-11e6-9d8c-c5c7f22c2390.png)

If I start change the exposure to above 0.9 I can begin to see the ladder:

exposure of 0.9:

![screen shot 2016-07-15 at 14 05 29](https://cloud.githubusercontent.com/assets/7610184/16888706/9a3cd17a-4a96-11e6-8776-cfcf3d953757.png)

exposure of 0.99:

![screen shot 2016-07-15 at 14 05 46](https://cloud.githubusercontent.com/assets/7610184/16888514/4fee17e2-4a95-11e6-887e-934bd982d3cb.png)

exposure of 1:

![screen shot 2016-07-15 at 14 06 48](https://cloud.githubusercontent.com/assets/7610184/16888523/658d4d66-4a95-11e6-8bb9-3d5db844ecaf.png)

I think this may be an issue with the way quantities of DNA are calculated in the gel module. Causing them to be much higher than the ladder concentrations.

I found that a quick work-around is to ajust the following setting, in line 457 of gel.py:

    def weight_standard_sample(key, qty=Q_(10000, 'ng')):  # originally 500

which if run as the following:

    pydna.Gel([st, [pcr_prod]]).run()

Produces the following:

![screen shot 2016-07-15 at 14 14 29](https://cloud.githubusercontent.com/assets/7610184/16888683/7bb8eae0-4a96-11e6-9b10-e433ac3e5342.png)

**Comment by BjornFJohansson** [comment]
Hi, an thanks for the bug report. I have som code to fix this that I will incorporate in the next version.
probably out before the end of the month.

BTW, this will be a python3 version

**Comment by FinweNoldoran** [comment]
Great that's good to hear. I look forward to the next version.

**Comment by BjornFJohansson** [comment]
This has been fixed in the latest release. Please reopen if not.
