### ISSUE TITLE
Simplify Dseq.init

### ISSUE THREAD

**Issue by JeffXiePL** [BjornFJohansson/pydna#240]
The code here could be simplified to a if >= statement

https://github.com/BjornFJohansson/pydna/blob/989e76eec0e46775aac7df1cab7c957834117608/src/pydna/dseq.py#L343-L347

**Comment by BjornFJohansson** [comment]
I agree! nice work!

**Comment by BjornFJohansson** [comment]
Ill close this as this was fixed.
