### ISSUE TITLE
Add codecov token

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#242]
Hi @BjornFJohansson, I think you may have add the codecov token to the repository. I can't see on my side if you have added it.

Below is the explanation on how to do it.

https://docs.codecov.com/docs/adding-the-codecov-token

This caused this action to fail https://github.com/BjornFJohansson/pydna/actions/runs/9942066709/job/27467718816

With this error:

```
{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1853s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1850s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1848s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1846s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1844s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1842s.', code='throttled')}
```

**Comment by BjornFJohansson** [comment]
I think it should be there already? 

![image](https://github.com/user-attachments/assets/6eb35491-eaac-46a6-a15c-4b407faa1aca)

**Comment by manulera** [comment]
I think the issue here then might have to do with the pull request coming from a forked repository? Not sure if there is a safe way to let the actions coming from forked repositories to use the token. Did this come up before?

**Comment by manulera** [comment]
This seems to be a problem that other people have, and I have not managed to find a simple solution:

https://github.com/codecov/feedback/issues/358

**Comment by manulera** [comment]
Actually fixed by updating the version of the action in https://github.com/BjornFJohansson/pydna/commit/fd8577c3e0e7479d86cbfff43576ba1040e32744
