### ISSUE TITLE
PCR not specific error report for a pair of specific primers 

### ISSUE THREAD

**Issue by JeffXiePL** [BjornFJohansson/pydna#256]
#244 

Hello, I had been writing documentation for a Gibson Assembly example, and I couldn't figure out why I am getting this "PCR not specific!" error message. I have checked that my primer sequences are specific to the vector. I have linked my code snippet here, which includes the error message: https://github.com/JeffXiePL/pydna/blob/dca58765c5920f7da0641e0d7ce06e233b23bee8/docs/notebooks/Example_Gibson.ipynb#L538C3-L565C5. 

Thank you,
Peilun

**Comment by manulera** [comment]
Hi @JeffXiePL this was hard to debug for a newcomer! I document this in the PR https://github.com/JeffXiePL/pydna/pull/4

**Comment by manulera** [comment]
Closing as it's fixed already
