### ISSUE TITLE
Add google collab functionality to documentation notebooks

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#266]
Hi @hiyama341 @jeffXiePL

One thing that could be done during the hackathon is to add the collab functionality to the notebooks that @jeffXiePL created.
https://github.com/JeffXiePL/pydna/tree/docs_peilun/docs/notebooks

@jeffXiePL this is a way for people to be able to run the notebooks in the browser without having to install dependencies. There is an example in @hiyama341's notebook here: https://github.com/hiyama341/teemi/blob/main/colab_notebooks/00_1_DESIGN_Homologs.ipynb

You have to create a cell that install the dependencies, and something else to add the badge to open the notebook. This is an easy one, but could be quite helpful.

**Comment by hiyama341** [comment]
I'll have a look at this first :)
