### ISSUE TITLE
Enable adding spacer to assembly_fragments

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#269]
Hi @BjornFJohansson,

I think it would be nice if we allowed adding spacers to the primers generated by `assembly_fragments`, so that they contain an extra sequence between the part that binds to the PCR template and the homology region. This could be an extra argument to `assembly_fragments` that by default is `None` and otherwise contains a list of the spacers that should go between sequences.

**Comment by manulera** [comment]
@hiyama341 maybe you have some thoughts on this?

**Comment by hiyama341** [comment]
Hi Manu, this is such a good idea that will really make some of the things that we are doing easier. For many projects, I have had to append these spacers so this is super helpful. Have you set a limit to the length of spacer you would incorporate into the primers btw? Looking forward to hearing from you.

**Comment by BjornFJohansson** [comment]
This works, see #288
