### ISSUE TITLE
Error in annotation for PCRs

### ISSUE THREAD

**Issue by manulera** [BjornFJohansson/pydna#279]
Hello @BjornFJohansson I noticed an error when transferring features from the PCR template to the product. I have fixed it in [this commit](https://github.com/BjornFJohansson/pydna/commit/e87d85a4be47d43a504a4bf75dd61cb536a8e0e3).

See amplify and utils.

Basically, if the primer had a tail, the features were not being shifted. Will add a test for this

**Comment by BjornFJohansson** [comment]
Is this a part of a coming merge?

**Comment by manulera** [comment]
Hi @BjornFJohansson,

The fix is in an upcoming branch yes. As of now it's in the linked commit part of the PR #278

> I made a branch called primerdesignbug, not sure how to link it here. It has a solution to allow the original example to run with very short primers. I saw that the example was updated with longer primers which is maybe a good idea. I would still want the original example to run.

From what I can see in `primerdesignbug`, the fix you included is different from what I was mentioning here, so I thin you can probably just create a PR for that.

**Comment by manulera** [comment]
This was still failing in circular sequences. I fixed that for
