### ISSUE TITLE
pypandoc error during install with pip

### ISSUE THREAD

**Issue by mcrone** [BjornFJohansson/pydna#33]
Just wanted to make sure I'm not missing something obvious. I'm trying to install pydna on Oracle Linux and I get this error: RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

It's a pypandoc error. Any help on how to get past this would be awesome!

Thanks!

**Comment by BjornFJohansson** [comment]
Hi, which version are you trying to install? Are you using Anaconda or system Python?
There might be a dependency missing. Could you paste the entire traceback here, please.

**Comment by mcrone** [comment]
I'm just using the system python and just using `sudo pip install pydna`

This is the traceback:
`Collecting pydna
  Using cached pydna-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jt61RH/pydna/setup.py", line 32, in <module>
        long_description=read_md('README.md'),
      File "/tmp/pip-build-jt61RH/pydna/setup.py", line 14, in <lambda>
        read_md = lambda f: convert(f, 'rst')
      File "/usr/lib/python2.7/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jt61RH/pydna/
`

**Comment by BjornFJohansson** [comment]
I see, first problem is that you have python 2.7, while pydna now only works with python 3.
perhaps if you use pip3 instead of pip? or have a look at this: http://stackoverflow.com/questions/29712519/how-do-i-use-pip-3-with-python-3-4

Some dependencies like numpy etc will not be installed automatically. Have you tried Anaconda?
Is solves many of these problems.

**Comment by mcrone** [comment]
Thanks for the help. I'll just try anaconda. I had previously had a bad experience with anaconda messing with my system python and that was why I was trying to avoid it (although that was under OSX).
