### ISSUE TITLE
Not working after pip installation

### ISSUE THREAD

**Issue by klprint** [BjornFJohansson/pydna#42]
Hi,

I am on macOS sierra. When I install pydna using `pip3 install pydna`, the installation quits successfully but after `import pydna` I can not run the example in your README.

```python
import pydna
seq = pydna.Dseq("GGATCCAAA","TTTGGATCC",ovhg=0)
```

output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pydna' has no attribute 'Dseq'
```

So, importing works but all available options when I tab-complete `pydna.` are:
```python
>>> pydna.
pydna.get_env(              pydna.open_config_folder(
pydna.logo                  pydna.open_current_folder(
pydna.open_cache_folder(    pydna.open_log_folder(
```

any suggestions?

**Comment by hsiaut** [comment]
Hi @klprint, I'm able to replicate this issue on my macbook air sierra (10.12.5 (16F73)) with python 3.5
using pip or conda

It looks like __init__ is not importing anything from all.py or any of the other module classes?


If I do the following instead, the code example works

`
from pydna import dseq
dseq.Dseq("GGATCCAAA","TTTGGATCC",ovhg=0)

#on IDLE returns 
>Dseq(-9)
>GGATCCAAA
>CCTAGGTTT
`

**Comment by klprint** [comment]
Interesting @hsiaut, I am using Python 3.6.1 and when I try the same, I can reproduce this.

**Comment by klprint** [comment]
A quick and dirty workaround would be the explicit import of the needed functions/classes. I just copied them from previous versions of pydna into the __init__.py file:

```python
from pydna.amplify    import Anneal
from pydna.amplify    import pcr
from pydna.amplify    import nopcr

from pydna.assembly   import Assembly

from pydna.genbank    import Genbank
from pydna.genbank    import genbank

from pydna.download   import download_text

from pydna.dseq       import Dseq
from pydna.dseqrecord import Dseqrecord

from pydna.readers    import read
from pydna.readers    import read_primer

from pydna.parsers    import parse
from pydna.parsers    import parse_primers

from pydna.editor             import Editor
from pydna.common_sub_strings import common_sub_strings

from pydna.design      import *  # I modified this, because the structure has changed of this submod.

from pydna.design      import primer_design
from pydna.design      import assembly_fragments

from pydna.utils              import eq
from pydna.utils              import shift_origin
from pydna.utils              import pairwise
from pydna.utils              import cseguid

from pydna.genbankfixer       import gbtext_clean
``

**Comment by BjornFJohansson** [comment]
Hi, sorry for the late reply, I am on vacation and I don't have internet most of the time.
I removed the import statements in the __init__.py file awhile back. I did this not to contaminate the namespace with stuff that maybe few people use.

Try 
```
from pydna.all import *
```

**Comment by BjornFJohansson** [comment]
I have fixed the readme examples so that they should work. Please let me know if you find other errors.

**Comment by klprint** [comment]
ah, great, thank you!
