### ISSUE TITLE
plasmid with feature crossing the ori

### ISSUE THREAD

**Issue by picousse** [BjornFJohansson/pydna#48]
Hi,
I seem to have found a bug concerning the reading of files with features crossing the ori using
gbs = pydna.parsers.parse(l, ds=True)

When the feature does not cross the ori, there is no problem. If I rotate the plasmid and a feature spans over the ori, then I don't seem to be able to read the file anymore.

Is this this a bug?

Any suggestion.
I'm also looking to properly annotate sequences.
Parts that cross the ori, are very poorly annotated (to not say incorrectly).

best regards,
Pieter

**Comment by picousse** [comment]
I've updated the dependencies, and now at least i get an error:
BiopythonParserWarning: Ignoring invalid location: '2390..324'

and the sequence was read.
For me this is the most important, however, there is still a problem there

**Comment by BjornFJohansson** [comment]
Hi @picousse 
Thanks for your feedback, Do you have code that can reproduce your problem?
I am working on a new release, so I would like to fix as many bugs as I can.

**Comment by picousse** [comment]
Hi,
seems everything is resolved now. I've update biopython and the dependencies, but also importantly, I've updated snapgene to 4.2. There was, so it seems, a convention problem which is now resolved.

everything seems to be owkay now, and working as expected.
Nice work with module! Like it lot.

Just looking in to the annotation now.

**Comment by Zulko** [comment]
Hi there,

For info, this might have been due to [that biopython 1.71 bug](https://github.com/biopython/biopython/issues/1608). The solution is indeed to upgrade Biopython, but beware that as of biopython 1.72, the location info of your cross-origin feature will normally be lost.

**Comment by BjornFJohansson** [comment]
Hi  @Zulko 
Are we talking about this kind of file, where star>stop ?

```
LOCUS       New_DNA                   10 bp ds-DNA     linear       31-AUG-2018
DEFINITION  .
ACCESSION   
VERSION     
SOURCE      .
  ORGANISM  .
FEATURES             Location/Qualifiers
     misc_feature    8..3
                     /locus_tag="NewFeature"
ORIGIN
        1 accgggtttt     
//
```
