### ISSUE TITLE
Including in Biopython?

### ISSUE THREAD

**Issue by photocyte** [BjornFJohansson/pydna#50]
Hi there,

Thank you for making pydna.  I've had fun using it to automate some cloning reactions.

It seems like pydna is something that really should exist in Biopython proper.  Have you talked to those developers to see if they would be interested in including it?

All the best,
-Tim

**Comment by BjornFJohansson** [comment]
Thanks for your interest in pydna. I have thought about approaching the biopython team about this but I have not got around to do that yet. It would certainly facilitate installation for most people. Meanwhile I am working on a new release with a slightly redesigned assembly protocol. After finishing that I might see what the biopython people think.
