### ISSUE TITLE
SeqRecord has no attribute ...

### ISSUE THREAD

**Issue by willsharpless** [BjornFJohansson/pydna#52]
Hi thanks a ton for making PyDNA, its awesome. I am having this error maybe because I am a dumbass or because of a bug but if you would please help me that would be great. For some reason I am receiving the attribute error: 'SeqRecord' object has no attribute 'list_features' and same for any of the attributes I've tried. I've opened up the seqrecord.py file and included a screenshot below; I have not tampered with this file in any way. What's weird is that dir(SeqRecord) will show me the attributes (I was wondering if it was getting confused with the Bio.SeqRecord but it doesn't seem to be so).

![image](https://user-images.githubusercontent.com/52509586/60978757-7b84f680-a2e6-11e9-9cdb-811b0e0c0a6e.png)

![image](https://user-images.githubusercontent.com/52509586/60979268-3f9e6100-a2e7-11e9-9dfa-fec72b6a2708.png)

![image](https://user-images.githubusercontent.com/52509586/60979303-4fb64080-a2e7-11e9-9ff6-c637f34db750.png)

![image](https://user-images.githubusercontent.com/52509586/60979383-7c6a5800-a2e7-11e9-8416-c1feb647d08d.png)

![image](https://user-images.githubusercontent.com/52509586/60979487-a9b70600-a2e7-11e9-9bdf-316351f296b7.png)

**Comment by willsharpless** [comment]
StackOverflow suggests that it might be because of most updated python's error related to a combination of tabs and spaces

**Comment by BjornFJohansson** [comment]
Hi, It is because the SeqRecord of pydna is slightly more capable than the SeqRecord of Bio.
look at this [notebook](https://gist.github.com/BjornFJohansson/eac1b9f7d53326c5116b52c32b064d45).
The Bio.SeqIO gives you a Bio.SeqRecord. In the notebook above I transferred all the properties to the pydna.SeqRecord which is one way to do it.

**Comment by willsharpless** [comment]
Bjorn you are bomb.com
