### ISSUE TITLE
Pictures in the docs, is this possible to print:

### ISSUE THREAD

**Issue by willsharpless** [BjornFJohansson/pydna#54]
Is there anyway to display the figures you have below the code in the pictures below, or did you just draw this out by hand? Some of my assemblies are being weird/I am trying to learn the package, and it would be useful for troubleshooting and general purpose if the ascii figures were built in attributes for both common_sub_strings and terminal_overlap.

![image](https://user-images.githubusercontent.com/52509586/61089934-a8720000-a3f1-11e9-915d-84774a8dc54a.png)

![image](https://user-images.githubusercontent.com/52509586/61089829-38637a00-a3f1-11e9-9f9d-fabf8ea4668d.png)

**Comment by BjornFJohansson** [comment]
These figures were hand drawn. There are the methods figure() and detailed_figure() for the 
`Contig` class: [here](https://pydna.readthedocs.io/#pydna.contig.Contig). The Assembly methods
assemble_linear and assemble_circular returns a list of `Contigs`.

**Comment by willsharpless** [comment]
Right I was using those and it gave me hope. Do you think it would be too tedious to implement those? I think it would be highly valuable.

**Comment by BjornFJohansson** [comment]
you mean for the common_sub_strings? This would probably not be very difficult. Could you give me 
a mock up of what you have in mind?

**Comment by willsharpless** [comment]
Well what if upon calling the common_sub_strings and terminal overlap functions there was a figure paramater which if == True would print the figures you drawn by hand above?

**Comment by BjornFJohansson** [comment]
Hi, this ended up on the backburner. Do you still need this?
Should be rather easy to implement.
