### ISSUE TITLE
Undesirable spaced letters when naming features and listing them

### ISSUE THREAD

**Issue by willsharpless** [BjornFJohansson/pydna#55]
Minor bug:

I tried to name my new features by changing the label value and for whatever reason the string becomes s p a c e d when you list_features():

![image](https://user-images.githubusercontent.com/52509586/61143248-870f2380-a486-11e9-966d-ef4e5734e7e1.png)
![image](https://user-images.githubusercontent.com/52509586/61143262-90988b80-a486-11e9-8729-577f9cb2bd84.png)

This does NOT happen when extracting features from a gb file:
![image](https://user-images.githubusercontent.com/52509586/61143308-ac9c2d00-a486-11e9-9a1d-c5a37bbd9c31.png)

**Comment by BjornFJohansson** [comment]
The feature qualifiers is a dictionary of lists, so you need to say

`s.features[0].qualifiers["label"] = [str(pro)]`

**Comment by BjornFJohansson** [comment]
btw have you seen my collection of [examples](https://github.com/BjornFJohansson/pydna-examples)

**Comment by willsharpless** [comment]
Sweet.  I have not seen the examples, but looks cool thanks.
