### ISSUE TITLE
pydna.gel  not work with pycharm editor 

### ISSUE THREAD

**Issue by mohamedmoez1983** [BjornFJohansson/pydna#58]
Dear sir 

Good  day to you

First I need to appreciate you for your pydna module, really  it is very useful module for every body study  molecular  biology but I have fin critical  issue when i run Gel class from pydna.gel on the pycharm editor not give any result (figure of gel electrophoresis) and also the same issue with original python IDLE however when i run it with Wing IDE make a conflict with Tkinter module 

Best regards

Yours sincerely
Mohamed Abdelmoez Ahmed Soliman
Bioinformatics  Researcher

**Comment by BjornFJohansson** [comment]
Hi,
Sure, I can try to help.
What problems do you get?
did you try it out in the jupyter notebook?
What is the version you are using?

**Comment by mohamedmoez1983** [comment]
Hi, Sir
thank you very much for quick response
when i run Gel class from pydna.gel module on the pycharm editor not give any result (figure of gel electrophoresis) 
i did not use  jupyter notebook but i will try it and inform you the result
i use  last stable version 3.0.1 also i tried 3.0.2a1 gave me the same result
