### ISSUE TITLE
Entering β in the description of a Dseqrecord causes an exception when using the write method

### ISSUE THREAD

**Issue by ITS-Account** [BjornFJohansson/pydna#71]
Aside from removing the β character from the description are there any possible solutions to this error?

This is the value that the descriptions holds:
`out_pydna.description
'30-506915946-NGS000053 with BβaI, GTGT/AGCC'`

Exception that occurs when utilizing the `out_pydna.write(path\to\some\gb\file.gb, f='gb')` method:
`Exception has occurred: UnicodeEncodeError
'charmap' codec can't encode character '\u03b2' in position 122: character maps to <undefined>`

I attempted to encode the description value to `utf-8`, but got the following error:
`Exception has occurred: TypeError
can't concat str to bytes`

Any help would be appreciated.

~ Cheers

Marcelo

**Comment by BjornFJohansson** [comment]
Thanks for your input! I'll have a look at this right away.

**Comment by BjornFJohansson** [comment]
I tried to replicate the issue using the latest version (4.0.0a10):

https://gist.github.com/BjornFJohansson/7c3caa7e521e64a32e274df573fefa34

It seems to work?

**Comment by ITS-Account** [comment]
Hey @BjornFJohansson, sorry for the late reply. I'm using version 3.1.3 which was installed via pip: 
`pip install pydna`
I'll try upgrading and get back to you.

**Comment by BjornFJohansson** [comment]
Try `pip install pydna==4.0.0a12`

**Comment by ITS-Account** [comment]
I tried that and still got the same error. I made a comment in the gist: https://gist.github.com/BjornFJohansson/7c3caa7e521e64a32e274df573fefa34#gistcomment-3886736

**Comment by BjornFJohansson** [comment]
I think I might have solved this bug. Try pip install `pydna==4.0.0a13` I have not been able to test manually on windows, but all tests pass on all platforms.

**Comment by ITS-Account** [comment]
@BjornFJohansson  I was still getting the same error after https://github.com/BjornFJohansson/pydna/commit/58de04def891e8dc36056b8760510398fcc47496. I added some missing encodings and now it works!

**Comment by BjornFJohansson** [comment]
Thanks for the PR. I added it to version 4.0.0a14.

**Comment by ITS-Account** [comment]
Sweet, thanks. I'll close this issue now.
