### ISSUE TITLE
Error on import during setup of environment variables with v4.0.0 and above

### ISSUE THREAD

**Issue by osthomas** [BjornFJohansson/pydna#74]
Hi, thanks for providing pydna!

I recently performed an update (long overdue) and found that I could no longer import `pydna` (under Linux, pydna installed via pip). It works up to and including version 3.1.3.
The error occurs during the setup of environment variables.
    
    >>> import pydna
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/oliver/pydnatest/lib/python3.9/site-packages/pydna/__init__.py", line 196, in <module>
        _os.environ[f"pydna_{key}"] = _os.getenv(f"pydna_{key}",
      File "/usr/lib/python3.9/os.py", line 684, in __setitem__
        value = self.encodevalue(value)
      File "/usr/lib/python3.9/os.py", line 756, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not PosixPath

Specifically, it fails at the "enzymes" key of the `default_ini`, whose value is a `PosixPath` and not `str`. Casting this to `str` resolves the error.

Interestingly, it doesn't fail for the "primers" key, for which `_os.getenv(f"pydna_{key}"` returns an empty string for me (and not `None`), so the default is not used. I'm not sure where that comes from, I never touched it.

**Comment by BjornFJohansson** [comment]
Hi, Ill have a look at this. could you give me the version of pydna and the content of the pydna.ini?

**Comment by osthomas** [comment]
Actually, that seems to have been the culprit. I appear to have had an old pydna.ini, probably generated from an older version of pydna (see below). There is also an empty entry for the primers key in there, though as I said, I have never touched that file. In the new default pydna.ini, there are paths for both `enzymes` and `primers`, which I assume are read in as strings and thus don't cause the error.

The pydna version is 4.0.2, but I also checked 4.0.0, and I got the same error. It worked with 3.1.3.


**Old pydna.ini:**

    [main]
    loglevel = 30
    email = someone@example.com
    data_dir = /home/oliver/.local/share/pydna
    log_dir = /home/oliver/.cache/pydna/log
    cache = cached
    cached_funcs = Genbank_nucleotide #Anneal,Assembly,download_text,Dseqrecord_synced,Genbank_nucleotide
    ape = put/path/to/ape/here
    primers = 


**New pydna.ini:**

    [main]
    loglevel = 30
    email = someone@example.com
    data_dir = /home/oliver/.local/share/pydna
    log_dir = /home/oliver/.cache/pydna/log
    cached_funcs = pydna.genbank.genbank.nucleotide
    ape = put/path/to/ape/here
    primers = /home/oliver/.local/share/pydna/primers.md
    enzymes = /home/oliver/.local/share/pydna/enzymes.md
    primersgdoc = PRIMERS

**Comment by BjornFJohansson** [comment]
Thanks! I'll see if I can catch this in the future.

**Comment by BjornFJohansson** [comment]
@osthomas, the new pydna 4.0.5 can handle missing keys in the pydna.ini more robustly. Thanks for the input.
