### ISSUE TITLE
primer_design() not able to run

### ISSUE THREAD

**Issue by nick-chavez23** [BjornFJohansson/pydna#90]
I am reporting a problem with pydna version, Python version, and operating
system as follows:

3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
CPython
Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
4.0.7

###Expected behaviour
function primer_design() outputs an optimized set of primers for a sequence

###Actual behaviour
[/usr/local/lib/python3.7/dist-packages/Bio/SeqRecord.py](https://localhost:8080/#) in reverse_complement(self, id, name, description, features, annotations, letter_annotations, dbxrefs)
1234 # Default to DNA)
1235 seq = self.seq.reverse_complement(
-> 1236 inplace=False
1237 ) # TODO: remove inplace=False
1238 if isinstance(self.seq, MutableSeq):

TypeError: reverse_complement() got an unexpected keyword argument 'inplace'

It looks like there may be a test that stayed in the final function that does not allow this function to be run.

**Comment by ThallitonSilva** [comment]
I have the same issue

**Comment by BjornFJohansson** [comment]
Thanks for your comments. LEt me see what is going on.

**Comment by BjornFJohansson** [comment]
Seems to work fine using your version of pydna. Can you submit a minimal example?


```
from pydna.design import primer_design
from pydna.dseqrecord import Dseqrecord

gene = Dseqrecord("atgactgaattcaaggccggttctgctaagaaaggtgctacacttttcaagactagatgtctacaatgccacaccgtggaaaagggtggcccacataaggttggtccaaacttgcatggtatctttggcagacactctggtcaagctgaagggtattcgtacacagatgccaatatcaagaaaaacgtgttgtgggacgaaaataacatgtcagagtacttgactaacccaaagaaatatattcctggtaccaagatggcctttggtgggttgaagaaggaaaaagacagaaacgacttaattacctacttgaaaaaagcctgtgagtaa")

ampl = primer_design(gene)

print(ampl.forward_primer.seq)

print(ampl.reverse_primer.seq)

from pydna import __version__ as v

print(v)

from Bio import __version__  as v

print(v)
```

output

```
runfile('/home/bjorn/Desktop/ypkpathway/src/ypkpathway/untitled0.py', wdir='/home/bjorn/Desktop/ypkpathway/src/ypkpathway')
atgactgaattcaaggcc
ttactcacaggcttttttca
4.0.7
1.79
```

**Comment by ThallitonSilva** [comment]
The error is actually in biopython, not pydna
Latest version of biopython 1.80

when I downgrade to version 1.79 everything works normally

**Comment by peterjc** [comment]
The error is in pydna due to an API change from Biopython 1.79 to 1.80, see https://github.com/biopython/biopython/issues/4177#issuecomment-1325784162

**Comment by BjornFJohansson** [comment]
Thanks for the input, Ill update pydna ASAP.

**Comment by peterjc** [comment]
I've not had a chance to see what needs changing in ``pydna`` - and if you would need to do anything complicated like a try/except to support both Biopython 1.80 onwards and Biopython 1.79 or older. Feel free to ask if you need assistance.

**Comment by nick-chavez23** [comment]
Thank you both for your help! I appreciate it greatly.

**Comment by BjornFJohansson** [comment]
Hi, I have fixes for biopython 1.80 that passes all the tests on my machine. I did not manage to set up github actions yet, for some reason i could not pin biopython to 1.80:

https://github.com/BjornFJohansson/pydna/actions

Ill try to fix this later this week, have to go and teach class now.

**Comment by BjornFJohansson** [comment]
@nick-chavez23  @ThallitonSilva the new 5.0.0 works with biopython 1.80 and also with python 3.11.
No conda package for python 3.7 but you can probably pip install.
If a conda package for 3.7 is needed, let me know.

**Comment by peterjc** [comment]
No conda-forge package for Biopython 1.80 either, conda-forge dropped support for Python 3.7 earlier this year.

**Comment by BjornFJohansson** [comment]
Solved in 5.2.0 I hope. Feel free to reopen if not.

**Comment by zslastman** [comment]
I am still getting this error:

```

In [2]: sys.version
Out[2]: '3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]'

In [3]: import Bio

In [4]: Bio.__version__
Out[4]: '1.81'

In [5]: import pydna.dseqrecord

In [6]: import pydna

In [7]: pydna.__version__
Out[7]: '5.5.0'


In [10]: pydna.dseqrecord.Dseqrecord('aaa').rc()
------------------------------------------------------------
TypeError                  Traceback (most recent call last)
Cell In[10], line 1
----> 1 pydna.dseqrecord.Dseqrecord('aaa').rc()

File ~/miniconda3/lib/python3.11/site-packages/pydna/dseqrecord.py:941, in Dseqrecord.reverse_complement(self)
    917 def reverse_complement(self):
    918     """Reverse complement.
    919 
    920     Examples
   (...)
    939 
    940     """
--> 941     answer = type(self)(super().reverse_complement())
    942     answer.name = "{}_rc".format(self.name[:13])
    943     answer.description = self.description + "_rc"

File ~/miniconda3/lib/python3.11/site-packages/pydna/seqrecord.py:144, in SeqRecord.reverse_complement(self, *args, **kwargs)
    142 def reverse_complement(self, *args, **kwargs):
    143     """Return the reverse complement of the sequence."""
--> 144     answer = super().reverse_complement(*args, **kwargs)
    145     answer = type(self).from_Bio_SeqRecord(answer)
    146     return answer

File ~/miniconda3/lib/python3.11/site-packages/Bio/SeqRecord.py:1238, in SeqRecord.reverse_complement(self, id, name, description, features, annotations, letter_annotations, dbxrefs)
   1233     seq = self.seq.reverse_complement_rna(
   1234         inplace=False
   1235     )  # TODO: remove inplace=False
   1236 else:
   1237     # Default to DNA)
-> 1238     seq = self.seq.reverse_complement(
   1239         inplace=False
   1240     )  # TODO: remove inplace=False
   1241 if isinstance(self.seq, MutableSeq):
   1242     seq = Seq(seq)

TypeError: Dseq.reverse_complement() got an unexpected keyword argument 'inplace'
```

**Comment by peterjc** [comment]
You have Biopython 1.81, it seems worth trying 1.80 as per the discussion above?

**Comment by manulera** [comment]
Sorry I did not see this.

@zslastman, I replied in your other issue #349 

Thanks for replying @peterjc !
